# Generated by Django 4.0.2 on 2022-02-24 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=999999999, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=999999999, max_length=10)),
                ('college_name', models.CharField(default='KL Vijayawada', max_length=30)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ECM', 'ECM'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('BT', 'BT'), ('BBA', 'BBA'), ('EEE', 'EEE'), ('BCA', 'BCA'), ('LAW', 'LAW'), ('MBA', 'MBA'), ('HOTEL MANG.', 'HOTEL MANG.'), ('FINE ARTS', 'FINE ARTS'), ('ARCH.T', 'ARCH.T'), ('OTHER', 'OTHER')], default='CSE', max_length=20)),
                ('year_of_study', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
