# Generated by Django 3.2.11 on 2022-03-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
    ]
